server:
  port: ${SERVER_PORT:8080}

spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/postgres
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
jpa:
  properties:
    hibernate:
      jdbc:
        lob:
          non_contextual_creation: true
        dialect: org.hibernate.dialect.PostgreSQLDi
      ddl-auto: none

  #Flyway properties
  flyway:
    enabled: true
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/postgres
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
